"""Current Oneirodex theme designs: dark rooms with distinct surface, type, motion, and icon language."""

PRESET_THEMES = [
    {
        'slug': 'greenhouse',
        'name': 'Mosslight',
        'description': 'A quiet green terminal room with phosphor edges and crisp, square controls.',
        'group': 'cabinet',
        'era': 'desk',
        'btn_primary': '#75e6a4',
        'btn_primary_hover': '#47cf82',
        'bg_dark_40': 'rgba(8, 24, 18, 0.96)',
        'bg_dark_30': 'rgba(5, 15, 12, 0.98)',
        'icon_pack': 'outline',
        'tokens': {
            'od-text': '#effcf4', 'od-text-muted': '#9fcdb0',
            'od-border': 'rgba(117, 230, 164, 0.2)', 'od-accent-2': '#b5f5ce',
            'od-glass-bg': 'rgba(8, 30, 20, 0.84)', 'od-glass-border': 'rgba(117, 230, 164, 0.25)',
            'od-glass-blur': '5px', 'od-crt-opacity': '0.035', 'od-tile-gap': '10px',
            'font-display': '"Segoe UI Semibold", "Segoe UI", sans-serif',
            'font-ui': '"Segoe UI", "Helvetica Neue", sans-serif',
            'od-icon-stroke': '2', 'od-icon-linecap': 'round', 'od-icon-linejoin': 'round',
            'od-icon-fill': 'none', 'od-icon-fill-opacity': '0',
        },
    },
    {
        'slug': 'afterglow',
        'name': 'Afterglow Arcade',
        'description': 'A neon cabinet with marquee pink, electric cyan, and stepped pixel details.',
        'group': 'cabinet',
        'era': 'arcade_cabinet',
        'btn_primary': '#ff5b9b',
        'btn_primary_hover': '#ed347e',
        'bg_dark_40': 'rgba(25, 9, 23, 0.96)',
        'bg_dark_30': 'rgba(13, 5, 15, 0.98)',
        'icon_pack': 'pixel',
        'tokens': {
            'od-text': '#fff0f6', 'od-text-muted': '#f6a7c9',
            'od-border': 'rgba(255, 91, 155, 0.24)', 'od-accent-2': '#65eaff',
            'od-glass-bg': 'rgba(34, 9, 29, 0.84)', 'od-glass-border': 'rgba(255, 91, 155, 0.31)',
            'od-glass-blur': '7px', 'od-crt-opacity': '0.075', 'od-tile-gap': '9px',
            'font-display': '"Arial Black", "Segoe UI", sans-serif',
            'font-ui': '"Segoe UI", "Helvetica Neue", sans-serif',
            'od-icon-stroke': '2.6', 'od-icon-linecap': 'square', 'od-icon-linejoin': 'miter',
            'od-icon-fill': 'currentColor', 'od-icon-fill-opacity': '0.72',
        },
    },
    {
        'slug': 'monochrome',
        'name': 'Graphite Studio',
        'description': 'A restrained studio interface with paper-white marks, hard edges, and no glow.',
        'group': 'cabinet',
        'era': 'desk',
        'btn_primary': '#d9e0e8',
        'btn_primary_hover': '#b9c4d0',
        'bg_dark_40': 'rgba(20, 23, 28, 0.97)',
        'bg_dark_30': 'rgba(11, 13, 17, 0.99)',
        'icon_pack': 'mono',
        'tokens': {
            'od-text': '#f5f7fa', 'od-text-muted': '#a8b0ba',
            'od-border': 'rgba(220, 230, 240, 0.15)', 'od-accent-2': '#c8d3df',
            'od-glass-bg': 'rgba(24, 28, 34, 0.92)', 'od-glass-border': 'rgba(220, 230, 240, 0.18)',
            'od-glass-blur': '0px', 'od-crt-opacity': '0', 'od-tile-gap': '10px',
            'font-display': '"Segoe UI", "Helvetica Neue", sans-serif',
            'font-ui': '"Segoe UI", "Helvetica Neue", sans-serif',
            'od-icon-stroke': '1.8', 'od-icon-linecap': 'square', 'od-icon-linejoin': 'miter',
            'od-icon-fill': 'currentColor', 'od-icon-fill-opacity': '0.42',
        },
    },
    {
        'slug': 'signal',
        'name': 'Signal Room',
        'description': 'Warm timber, amber standby lights, and tactile cartridge-era geometry.',
        'group': 'cabinet',
        'era': 'wood_den_80s',
        'btn_primary': '#f1b85b',
        'btn_primary_hover': '#d99338',
        'bg_dark_40': 'rgba(29, 20, 13, 0.96)',
        'bg_dark_30': 'rgba(17, 11, 8, 0.98)',
        'icon_pack': 'filled',
        'tokens': {
            'od-text': '#fff5e8', 'od-text-muted': '#d8b98d',
            'od-border': 'rgba(241, 184, 91, 0.22)', 'od-accent-2': '#ffda9b',
            'od-glass-bg': 'rgba(39, 24, 13, 0.86)', 'od-glass-border': 'rgba(241, 184, 91, 0.27)',
            'od-glass-blur': '4px', 'od-crt-opacity': '0.07', 'od-tile-gap': '8px',
            'font-display': '"Trebuchet MS", "Segoe UI", sans-serif',
            'font-ui': '"Segoe UI", "Helvetica Neue", sans-serif',
            'od-icon-stroke': '1.8', 'od-icon-linecap': 'square', 'od-icon-linejoin': 'round',
            'od-icon-fill': 'currentColor', 'od-icon-fill-opacity': '0.82',
        },
    },
    {
        'slug': 'tape-deck',
        'name': 'Tape Deck',
        'description': 'A playful 90s bedroom palette with soft plastics, lavender, and rounded forms.',
        'group': 'cabinet',
        'era': 'teen_bedroom_90s',
        'btn_primary': '#c4a3ff',
        'btn_primary_hover': '#a981f0',
        'bg_dark_40': 'rgba(24, 17, 34, 0.96)',
        'bg_dark_30': 'rgba(13, 9, 20, 0.98)',
        'icon_pack': 'soft',
        'tokens': {
            'od-text': '#f8f1ff', 'od-text-muted': '#c6b0db',
            'od-border': 'rgba(196, 163, 255, 0.2)', 'od-accent-2': '#e2c9ff',
            'od-glass-bg': 'rgba(31, 20, 44, 0.82)', 'od-glass-border': 'rgba(196, 163, 255, 0.28)',
            'od-glass-blur': '12px', 'od-crt-opacity': '0.025', 'od-tile-gap': '12px',
            'font-display': '"Arial Rounded MT Bold", "Segoe UI", sans-serif',
            'font-ui': '"Segoe UI", "Helvetica Neue", sans-serif',
            'od-icon-stroke': '2.4', 'od-icon-linecap': 'round', 'od-icon-linejoin': 'round',
            'od-icon-fill': 'currentColor', 'od-icon-fill-opacity': '0.38',
        },
    },
    {
        'slug': 'deep-space',
        'name': 'Deep Space Media',
        'description': 'A cool silver-blue media centre with crisp glass, broad spacing, and angular icons.',
        'group': 'cabinet',
        'era': 'media_center_00s',
        'btn_primary': '#6ac7ff',
        'btn_primary_hover': '#37a9ed',
        'bg_dark_40': 'rgba(10, 19, 31, 0.97)',
        'bg_dark_30': 'rgba(5, 10, 18, 0.99)',
        'icon_pack': 'angular',
        'tokens': {
            'od-text': '#eef7ff', 'od-text-muted': '#a4c9e5',
            'od-border': 'rgba(106, 199, 255, 0.2)', 'od-accent-2': '#b7e4ff',
            'od-glass-bg': 'rgba(9, 24, 40, 0.74)', 'od-glass-border': 'rgba(106, 199, 255, 0.27)',
            'od-glass-blur': '16px', 'od-crt-opacity': '0.012', 'od-tile-gap': '13px',
            'font-display': '"Segoe UI Semibold", "Segoe UI", sans-serif',
            'font-ui': '"Segoe UI", "Helvetica Neue", sans-serif',
            'od-icon-stroke': '1.4', 'od-icon-linecap': 'square', 'od-icon-linejoin': 'miter',
            'od-icon-fill': 'none', 'od-icon-fill-opacity': '0',
        },
    },
]